### ISSUE TITLE
UTC everywhere

### ISSUE THREAD

**Issue by wtogami** [slickage/adness#21]
Auction times are displayed but it is unclear what timezone it is referring to.  Perhaps all times displayed should have a "UTC" suffix and somewhere near the top of every page is "Server Time: xxxxxxxx UTC"?

**Comment by taesup** [comment]
All times displayed on adness are in local time if scripting is enabled. If scripting is disabled, the times with a GMT offset are shown. General users will probably assume local time but verbiage stating that all times are in local time can be added.

**Comment by wtogami** [comment]
One can easily imagine auction result e-mail notifications will contain time.  How would it decide on timezone for the e-mail?  It would be confusing if that timezone differs from what they see in the the web view.

One way around this is to always use the same timezone or to allow users to set a timezone.

**Comment by wtogami** [comment]
Please treat these only as recommendations.  Perhaps there is a better way to handle this.

Short Term: Display UTC everywhere including in e-mail.  That is easy to implement and exact.
Long Term: Make users choose a timezone during registration.

In all cases display the time and timezone in the UI.

**Comment by theymos** [comment]
Make everything UTC everywhere, but add relative time onto every timestamp. Also get rid of the day name -- it'll rarely be accurate for the reader if we're using UTC.

Example:
"End: Thursday, May 22, 2014 12:00:00 AM"
becomes
"End: May 22, 2014 12:00:00 AM (2 days ago)"

**Comment by taesup** [comment]
I can change everything to UTC time but I'm not sure what you mean by relative time? Time relative to the user's local time? I can't get that if they have scripting disabled. Maybe it's best if I just used UTC everywhere in the ISO format: 

Mon, 26 May 2014 05:14:39 GMT 

Also the day name is relative to the GMT timezone. 

This is easiest because that's what naturally comes out of JS's datetime object. I can use an additional library on the backend to to format the date before it goes into the view but it requires a bit more work. 

As for the relative time, it would be quite a bit of work to get to work well in either case (local or UTC time), mainly because we'll need to handle whether the date is in the past or in the future and use appropriate wording. A simpler method would to show a time scale difference such as +00:02:00 but I'm not sure how valuable a relative time is to the user.

**Comment by theymos** [comment]
relative time = time relative to now. Like (2 hours ago) or (2 days
from now). This doesn't change per timezone, so it's more clear than
absolute times.

On Mon, May 26, 2014, at 04:42 AM, Edward Kim wrote:

  I can change everything to UTC time but I'm not sure what you mean
  by relative time? Time relative to the user's local time? I can't
  get that if they have scripting disabled. Maybe it's best if I just
  used UTC everywhere in the ISO format:

  Mon, 26 May 2014 05:14:39 GMT

  Also the day name is relative to the GMT timezone.

  This is easiest because that's what naturally comes out of JS's
  datetime object. I can use an additional library on the backend to
  to format the date before it goes into the view but it requires a
  bit more work.

  As for the relative time, it would be quite a bit of work to get to
  work well in either case (local or UTC time), mainly because we'll
  need to handle whether the date is in the past or in the future and
  use appropriate wording. A simpler method would to show a time scale
  difference such as +00:02:00 but I'm not sure how valuable a
  relative time is to the user.

  —

Reply to this email directly or [1]view it on GitHub.

References
1. https://github.com/slickage/adness/issues/21#issuecomment-44173553

**Comment by wangbus** [comment]
@taesup We've used this in the past didn't we? http://momentjs.com/

**Comment by taesup** [comment]
@wangbus Yea that's the library I was talking about using on the backend. 

everyone else, If all the datetimes are going to be in UTC, should I also change the way the auction creation tools uses the datetime picker? It's currently using local time for the input dates and times.

**Comment by wtogami** [comment]
@taesup 
Yes, UTC everywhere.
