### ISSUE TITLE
View: Merge listing of Current and Past Auctions

### ISSUE THREAD

**Issue by wtogami** [slickage/adness#30]
Should Home display past auctions below the current open auctions?

Perhaps consider merging History into Home so it displays both open and past auctions in chronological order.  The combination view would be very informative to bidders placing their current activity within context of past events.

**Comment by theymos** [comment]
You can't actually see the final prices just from the auction listing, so you'll need to click a few links to get pricing info either way. It doesn't matter to me. Might as well leave it as it is if it's less work.

**Comment by wtogami** [comment]
My point here is there's no benefit to having current and past auctions on separate pages.  It is more informative to have them on the same page.

**Comment by taesup** [comment]
I believe from a UI perspective, it's better to have the two on different pages because each page accomplishes a different goal. Those that want to bid on auction have a specific page to find which auctions are open while users looking for past auctions have a separate page. Having both on the same page forced both users to one page and search for, or will need some way to sort the auctions. This is a bit more work than necessary for this version but would be a good view for the fully scripted version of this application.

**Comment by wtogami** [comment]
OK, that's good reason to consider this later.  Closing for now.
