### ISSUE TITLE
Auction Title

### ISSUE THREAD

**Issue by wtogami** [slickage/adness#37]
Multiple separate auctions will be active simultaneously, global and regional.  To make it possible to easily differentiate the auctions, the title of each auction must be visible in the  Active and History listings, within each individual action, and within any relevant notifications, invoice view during payment and e-mail receipt after payment.

The auction title could be programatically created by the type of auction (Global, Russia-only, US-ony, etc.)  We may consider making it a free-form field so it can be customized for any purpose or to make the very same code usable for manually created auctions that are something else entirely?

Let's discuss.

**Comment by taesup** [comment]
I can have a text field in the DB object just for title. As of right now, the auction title (hard coded) is just:

AuctionStatus + "Auction:" + auctionId

I could add the title field into this so that it appears as 

AuctionStatus +  "Auction: " + auctionId
AuctionTitle
AuctionGlobalization

As a single line text field it would be:

"Auction: " + AuctionID + " - " + AuctionTitle + (AuctionGlobalization)

**Comment by wtogami** [comment]
AuctionRegion would make more sense as a variable name.

As for how it looks in the various views let's discuss.

**Comment by taesup** [comment]
New Proposal for Auction Title:

Colored Span(Auction Region) + "Auction: " + AuctionId
Auction Text Field

**Comment by taesup** [comment]
No longer relevant with new auction region design.
