### ISSUE TITLE
Bid's float display

### ISSUE THREAD

**Issue by theymos** [slickage/adness#62]
On the bidding page, it displays 0.6 as 0.6000000000000001. Floating-point money values should be rounded to the nearest satoshi everywhere, and then any trailing zeros should be removed.

**Comment by theymos** [comment]
Also, attempting to bid 0.6 instead of 0.6000000000000001 results in "This bid is invalid... the closest valid amounts are 0.6 and 0.65".

**Comment by taesup** [comment]
For the purposes of this application, I believe the only valid values are in 0.05 increments starting from 0.5. So I will round to two decimal places.

**Comment by wtogami** [comment]
Perhaps "starting from 0.5" might not be a true assumption?  As more slots dilute the probability of being seen, and narrower geographic regions have more slots, it is possible the market price for some slots would be below 0.5 BTC.  It may be necessary to allow the ability to set a different minimum price per region.

**Comment by taesup** [comment]
The 0.5 number was what was given to me as a requirement. If the starting value starts to become an issue, we can make changes to the config file so that each region has it's own starting value and price increments. We can turn that into an issue when it becomes one. For the purposes of this bug, I'll keep it closed.
